server:
  port: 8081

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect