INSERT INTO TASK_TYPE (name, is_buddy_type)
VALUES ('Ekonomi och affärssystem', false),
        ('Din konsultprofil', false),
        ('Praktiskt att fixa', false),
        ('Din digitala setup', false),
        ('Uppstart', true),
        ('Efter kontraktskrivning', true),
        ('Veckan innan start', true),
        ('Första arbetsdagen', true),
        ('Att gå igenom', true),
        ('Träffa kollegor', true),
        ('Avstämning', true),
        ('Överlämning/Avslut', true);

-- Create a new person
INSERT INTO PERSON (name, email, is_active, mentee_id)
VALUES ('John Doe', 'john.doe@exsade.com', true, null),
    ('Buddy', 'buddy@exsade.com', true, 1);

INSERT INTO TASK (type_id, title, description, url)
VALUES
    (1, 'Ekonomi och affärssystem',
        'Vi använder Maconomy för tidrapportering, attestering, reseräkningar mm. Här hittar du lathundar mm.',
        'https://xlent.sharepoint.com/sites/Files/Lathundar%20Maconomy/Forms/AllItems.aspx'),
    (1, 'CSF Support och service',
        'XLENTs centrala support kallas CSF. Här hittar du frågor och svar om deras stöd.',
        'https://xcg.freshservice.com/support/solutions'),
    (1, 'Intranät',
        'Workplace är XLENTs intranät med nyheter, kultur och samverkansforum. Klicka runt en stund så ser du vad som finns.',
        'unsafe:%20https://xlent.workplace.com'),
    (1, 'Medarbetarresan',
        'Här kan du få en samlad bild över våra delprocesser för dig som anställd.',
        'https://xlent.sharepoint.com/sites/Medarbetarresan/SitePages/Medarbetarresan.aspx'),
    (1, 'Varumärkessidan',
        'XLENT koncernen består av många olika bolag och varumärken. På den här sidan hittar du info om varumärke, logotyper, mallar etc.',
        'https://xlent.sharepoint.com/sites/CentralSupportFunctions/SitePages/Varum%C3%A4rken.aspx'),
    (1, 'Bra länkar under din onboarding',
        'Under länksidan hittar du länkar som kan vara bra under din onboarding.',
        null),
    (1, 'XLUs arbetssätt',
        'Under kunskapsidan hittar du beskrivningar av olika arbetssätt som vi har inom XLU. Titta igenom och fråga din buddy eller någon kollega om det är något du undrar över.',
        null),
    (1, 'XLU Teams',
        'Teams används för internkommunikation inom XLENT Luleå och med kollegor i andra bolag.',
        'https://teams.microsoft.com/'),
    (2, 'Information konsultprofil',
        'Läs om vad en konsultprofil är och hur du skapar en sådan',
        'https://xlent.sharepoint.com/:p:/s/XLENTLule/EZCDlaCm-N5Esv-uBhnT5mkBoFyWY0j9cteIbkG4Ftbojg?e=W0b3Z8&wdLOR=cD9B8BF98-180A-3648-98D9-058AA8CFD83B'),
    (2, 'Skapa konsultprofil',
        'Skapa din konsultprofil/ditt konsultcv i Cinode • Lösen första inloggning: xlent123. Ordinarie lösenord till Cinode kommer i mejl',
        'https://app.cinode.com/xlent/login'),
    (2, 'Introduktion till konsultrollen',
        'På XLENT är vi alla konsulter. Kontakta Ola så får du en liten introduktion till konsultrollen. (Kommer även en presentation)',
        null),
    (3, 'Sjukvårdsförsäkring (frivillig)',
        'Anmäl till Söderberg o Partners om sjukvårdsförsäkring (om aktuellt)',
        'https://xlent.sharepoint.com/:w:/s/XLENTLule/EUt51L9p4mxDoD-RjVNC2TABijrsLrK8m_Yd5UqWHNQT9w?e=txmKxR&wdLOR=c88A72933-520A-C54B-8CC5-345D45D3EDB7'),
    (3, 'Foto till digitala plattformar',
        'Ladda upp foto: • I Office365 • På Workplace • I Cinode • I kanalen XLENT Luleå på Teams, under Files/Media/Bilder/Porträtt',
        null),
    (3, 'Ange chef på Workplace',
        'Ange Veronica som chef (under Redigera profil). Du får då åtkomst till flera grupper välj därefter ytterligare grupper att gå med i.',
        null),
    (3, 'Gå med i grupper på Workplace',
        'Rekommenderade grupper: • XLENT syns och hörs • Försäljning inom XLENT • Kompetensluncher • CSF informerar • Har du hört • Fråga XLENT',
        null),
    (3, 'Presentation Workplace',
        'Presentera dig på Workplace, i gruppen "Hej jag är ny”. Är du osäker så prata med någon kollega.',
        'https://xlent.workplace.com/'),
    (3, 'Presentation webbsida',
        'Skicka din bild till Tove Leijding som är centralt varumärkesansvarig så ordnar hon så att den läggs upp på XLENTs webbsida för Luleåkontoret.',
        'https://www.xlent.se/kontor/lulea'),
    (3, 'Presentation Instagram',
        'Be Sofia Flodmark skicka frågor för en presentation till Instagram. Skriv sedan en presentation och skicka den tillsammans med din bild till henne så lägger hon upp det på vår Instagram',
        'https://www.instagram.com/xlent_lulea/?next=%2F&img_index=1'),
    (3, 'Uppdatera personlig information i HR-system',
        'Se över ICE kontakten och ev. kontonummer. (My profile samt Manage personalinfo)',
        'https://www.sympahr.net/Index#/'),
    (3, 'Kontaktuppgifter',
        'Säkerställ att ditt telefonnummer och kostavvikelser finns på vår Wiki-sida "Anteckningsbok-XLU" i Teams',
        null),
    (3, 'Email signatur',
        'Skapa en signatur till email på dator och mobil',
        'https://xlent.sharepoint.com/sites/Files/Varumrken/Forms/AllItems.aspx?id=%2Fsites%2FFiles%2FVarumrken%2FXLENT%2FMailsignatur%2Ezip&parent=%2Fsites%2FFiles%2FVarumrken%2FXLENT'),
    (3, 'Foto till kontoret',
        'Vi sätter upp foton på våra anställda på kontoret. Se till att skriva ut ditt foto, sätt i ram och fixa så den kommer på plats på kontoret.',
        null),
    (4, 'Dator och mobil',
        'Se till att installera och få igång din dator och telefon.',
        null),
    (4, 'Kollegor i telefonboken (frivillig)',
        'Lägg till XLENT koncern...',
        null),
    (4, 'Har du all utrustning du behöver?',
        'Har du all utrustning du behöver? Om inte – kontakta IT-ansvarig Christian!',
        null),

-- Buddy tasks
    (5, 'Uppstarsmöte',
        'Har du haft ett uppstartsmöte med rekryterings- och onboardinggruppen? Om inte, boka in ett möte',
        null),
    (6, 'Kontaktuppgifter',
        'Lägg in telefonnummer, e-postadress, kostavvikelser och datumet för den nyanställdas första arbetsdag i Anteckningsbok-XLU på Teams.',
        null),
    (6, 'Välkomstmail',
        'Maila för att hälsa välkommen samt informera om dator, mobil o.dyl',
        'https://xlent.sharepoint.com/:w:/s/XLENTLule/EfhDBf3mhxRAqam-n8Ji_1gB1Wxr5AuD2FBQB3VgYAQIGw?e=Ccbdeh'),
    (6, 'Beställningar',
        'Be IT-ansvarig hjälpa med beställning av dator, mobil samt ev flytt av abonnemang',
        null),
    (6, 'Dörrtagg',
        'Beställ dörrtagg, via lokalansvarig, till kontoret med kod (fråga nyanställd om önskad kod).',
        null),
    (6, 'Konto till Cinode',
        'Beställ konto i Cinode - via Veronica',
        null),
    (6, 'Efterfråga CV',
        'Efterfråga CV som skickas till XLU (om det inte redan finns hos oss, ex i Teamtailor)',
        null),
    (6, 'Bild till CV',
        'Efterfråga bild till CV. Skicka den sedan till Tove Leijding för att anpassa till vår grafiska profil (svartvit)',
        null),
    (6, 'Lägga upp CV',
        'Lägg upp CV (skapa i word tillsammans med nyanställd) och lägg upp i Cinode',
        'https://app.cinode.com/'),
    (6, 'CV i kortform',
        'Skapa CV i kortform (oneslide) i Cinode',
        'https://app.cinode.com/'),
    (7, 'Mobilnummer till CSF Finance',
        'Maila mobilnummer till CSF Finance',
        'https://xlent.sharepoint.com/sites/CentralSupportFunctions/SitePages/CSF-Finance.aspx'),
    (7, 'Boka in XLU-lunch/fika',
        'Boka in på XLU-lunch/fika (I välkomstmailet står att det sker första dagen)',
        null),
    (7, 'Blommor',
        'Beställ blommor hem till den nyanställde (kostnad ca 350 kr + budavgift) Ex Interflora',
        null),
    (7, 'Onboardingappen',
        'Säkerställ att den nyanställde är upplagd onboardingappen',
        null),
    (7, 'Välkomstpåse',
        'Förbered välkomstpåse med handduk, laddare, lypsyl, penna, buff, vattenflaska, reflex',
        null),
    (7, 'Inför första arbetsdagen',
        'Säkerställ att du kan möta upp den nyanställde på kontoret på dennes första dag och att dennes utrustning finns på plats',
        null),
    (8, 'Startkit',
        'Lämna ut utrustning (dator, telefon m.m.) och tilldela en personlig låda',
        null),
    (8, 'Inloggningsuppgifter',
        'Lämna ut inloggningsuppgifter med engångslösenord',
        null),
    (8, 'Dörrtag och larm',
        'Information om larm till kontoret och lämna ut dörrtag + kod',
        null),
    (8, 'Teams',
        'Lägg till nyanställd i chatten XLU och som medlem i Teams-gruppen XLENT Luleå (och Tekniklabbet om utvecklare)',
        null),
    (8, 'Onbardingappen',
        'Informera om onboardingappen och skicka länk till inloggningssidan',
        null),
    (8, 'Regelbundna möten och kommande evenemang',
        'Bjud in den nyanställda till regelbundna möten och kommande evenemang',
        null),
    (9, 'Maconomy',
        'Gå igenom tidrapportering och grundläggande information. Informera om att CSF kommer kalla till informationstillfälle i närtid',
        'https://me50653-iaccess.deltekfirst.com/oauth'),
    (9, 'Benefits',
        'Gå igenom förmånsportalen Benefits. (Benefits har körning 20e varje månad, om nyanställd börjar omkring det datumet, avvakta att rättigheter och full tillgång till Benefits slår igenom innan denna genomgång',
        'https://signin.soderbergpartners.se/prompt?signin=JgZWmn8BWxcqqF7v'),
    (9, 'Fokusgrupper',
        'Informera om våra fokusgrupper',
        null),
    (9, 'Fotografering',
        'Informera om att fotografering samordnas ca 1 gång/år av rekryterings- och onboardinggruppen',
        null),
    (10, 'VD-info',
        'Be Veronica boka in ett möte för genomgång av affärsplan/årsplan, semester, personalhandboken och medarbetarresan med den nyanställda.',
        null),
    (10, 'Lokaler',
        'Be Katja informera om lokaler, inklusive kontaktuppgifter till larmföretag Norrlarm, dörrbadge, Norconsult, nyckel till soprum, konferensrum, kontaktuppgifter städ, fastighetsskötare.',
        null),
    (10, 'Profilshopen',
        'Be Emmy visa hur den nyanställde gör sin beställning från profilbutiken. Valfria produkter för max 700 kr',
        'https://xlent.promo.se/sv/xlent/'),
    (10, 'IT-policy',
        'Be Christian informera den nyanställda om vår IT-policy',
        null),
    (10, 'Tips och Trix Cinode',
        'Be Sofia Hjort-Labba visa tips och trix i Cinode',
        'https://app.cinode.com/'),
    (10, 'Hållbarhet',
        'Be Sofia Flodmark informera den nyanställda om hållbarhet på XLU',
        null),
    (10, 'Teams/Intern kommunikation',
        'Be Alexandra gå igenom hur vår interna kommunikation fungerar',
        null),
    (10, 'Sälj',
        'Be Ola gå igenom vår säljprocess',
        null),
    (10, 'Interna aktiviteter',
        'Be August berätta om Kosegruppa och våra interna aktiviteter',
        null),
    (10, 'Sociala medier',
        'Be Albin visa och berätta om våra sociala medier',
        null),
    (10, 'Arkitektur för appen',
        'Be Richard berätta om arkitekturen kring onboardingappen',
        null),
    (10, 'Introduktionsutbildning/konferens',
        'Informera om introduktionskonferensen inom koncernen och att den sker ca 2 ggr/år. Den nyanställda kommer få en inbjudan',
        null),
    (11, 'Avstämningar',
        'Kom överens med den nyanställda om hur och hur ofta ni ska ha avstämningar',
        null),
    (12, 'Coach-rollen',
        'Informera om coach-upplägget och vilka som är valbara som coach',
        null),
    (12, 'Val',
        'Se till så att den nyanställda väljer coach. När valet är klart, fyll i listan i Anteckningsbok-XLU på Teams',
        null),
    (12, 'Överlämning',
        'Lämna över till den valda coachen',
        null);

-- Assign each task to the new person
INSERT INTO PERSON_TASK (task_id, person_id, is_completed)
SELECT t.id, p.id, false
FROM TASK t
CROSS JOIN PERSON p;