CREATE TABLE TASK (
  ID BIGSERIAL PRIMARY KEY,
  TASKTYPE VARCHAR(255),
  URLTITLE VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  URL VARCHAR(255),
  COMPLETED BOOLEAN,
  PERSON_ID BIGINT
);


CREATE TABLE PERSON (
  ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR(255),
  EMAIL VARCHAR(255),
  ACTIVE BOOLEAN
);




