CREATE TABLE PERSON (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255),
  is_active BOOLEAN
);

CREATE TABLE TASK_TYPE (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE TASK (
  id BIGSERIAL PRIMARY KEY,
  type_id BIGINT REFERENCES TASK_TYPE(id),
  title VARCHAR(255),
  description VARCHAR(255),
  url VARCHAR(255)
);

CREATE TABLE PERSON_TASK (
  id BIGSERIAL PRIMARY KEY,
  task_id BIGINT REFERENCES TASK(id),
  person_id BIGINT REFERENCES PERSON(id),
  is_completed BOOLEAN
);



